### ISSUE TITLE
Dockerize application

### ISSUE THREAD

**Issue by hd4n** [BME-MIT-IET/iet-hf-2023-authentic#1]
Create a Docker container for the program.

**Comment by hd4n** [comment]
8ca2170f3aae373ec78253c2dcd0e36f5af34a35 fixes the path for the assets. To build, run `javac blind-virologists/citizens/*.java blind-virologists/effects/*.java blind-virologists/items/*.java blind-virologists/main/*.java blind-virologists/map/*.java blind-virologists/views/*.java  -d ../out` from `graphics/src`. To run, use `java main/Main` from `graphics/out`.

**Comment by tothdodo** [comment]
3e33eef84c1554b4ab490eca40e32d6cd57e5644 Dockerfile created. Debian environment is set. It uses openJDK 11 image. X11 installation is required to be able to run an application with graphics. After build, we can run our Dockerfile, which starts the application.

**Comment by hd4n** [comment]
20a3fd32d789ea0abee56f83d2a5cad739ad3b68 Added `docker_run.sh`. This script builds the container, and runs it with the required X11 parameters.

**Comment by tothdodo** [comment]
0a396d55a8438a5f61f6254b477a32d6df415415 Dockerization document added.
