### ISSUE TITLE
Non-functional characteristics measurements

### ISSUE THREAD

**Issue by bmcool123** [BME-MIT-IET/iet-hf-2023-authentic#5]
Mondok Zalán, Baksa Máté:
-Measuring performance
-Stress testing
-Usability testing
-Reliability
-Security

**Comment by mondokz** [comment]
https://github.com/BME-MIT-IET/iet-hf-2023-authentic/commit/0e81a0226f1433fc20d029a3fef5af102e92c473
Added performance measurements of CPU, Memory, Threads and Non-heap memory to non-functional-characteristics.md

https://github.com/BME-MIT-IET/iet-hf-2023-authentic/commit/4db99131ec78b2a20dc5cceebcd7cc0c5cc70573
Fixed directory structure

**Comment by mondokz** [comment]
https://github.com/BME-MIT-IET/iet-hf-2023-authentic/commit/bd646e0b6caf84213e1d8de0e001b8fe1e8c669d
Added reliability, security, usability, and stress test result.
