### ISSUE TITLE
Static analysis + Manual code review

### ISSUE THREAD

**Issue by mondokz** [BME-MIT-IET/iet-hf-2023-authentic#6]
(Baksa Máté, Mondok Zalán)
-Manual code analysis
-SonarCloud setup
-Codacy
-SonaLint IntelliJ extension

**Comment by bmcool123** [comment]
Manuális kód átvizsgálása során eltávolítottunk nem használt metódusokat, importokat
és konstruktorokat: 1101249dbadd8646ae508ad7b7f43c995c7e0abe

**Comment by bmcool123** [comment]
SonarCloud-ot nem tudtuk a repository-ra setupolni, mivel owner permission-ra van szükség.
Codacy-ba importáltuk a repositoryt és átvizsgáltuk a kapott eredményeket.

**Comment by bmcool123** [comment]
SonarLint IntelliJ extensiont telepítettük.

**Comment by bmcool123** [comment]
Elkezdjük a hibák javítását és kód javaslatok implementálását.

**Comment by bmcool123** [comment]
Fixed the recommendations by Codacy
8ed06ed77c4b39c3d7366485924c5a809f48ff99 - collapsed if statement in Virologist.java
d34c45a0ec4d7626cebcaf404a9aef2634c48426 - deleted unused and empty methods in Virologist.java
3959a39930307593ea6ffadd10f42000dc71aa2d - collapsed if statement in BearDance.java

**Comment by mondokz** [comment]
Fixed multiple instances of Random:
167027bf1b97ecf8769d4a83f1dc996154a6a523
0cf328a426437aaeb09afebf6b8d485ed0d40d4d
e4d6d5e645b34cf600d3f06e9434b061e1ca2db5
782f7dae9d71274d6e8cdd7fa6a065637093c31e
Fixed if statement:
66c11220c34fa786226552306ca6923318e68328

**Comment by bmcool123** [comment]
Fixed non-static method accessing static field:
0a896d4cde0d5b2f04bebb7ea150db542f7dc2e4
Fixed no deafult in switch:
7470392886217c40ffeec42f0504e48caac34c5e
Fixed public constructors:
1f197cc77189113f994af23023d580a00b13d875
5230654e42f0eea51935d48042afea9128d3b701
db05169aa0529a789563c5b8cd2aeb2ab2f6b798
Fixed parent field name shadow:
60f27f77ce6a4a119a23777461543b64d8bced28
Fixed missing override
3c03e902ae6c302eadd10a2cccfc39006afe10b0
